# Generated by Django 3.1.1 on 2020-10-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='resultPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
