# Generated by Django 3.1.1 on 2020-10-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0002_bouquet_resultprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_paper_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='flower_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='resultPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
