# Generated by Django 3.0.8 on 2020-08-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0003_bouquet_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='flower_count',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='ribbon_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='wrappingpaper_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
