# Generated by Django 3.1.1 on 2020-10-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0003_auto_20201019_1120'),
        ('bouquets', '0003_auto_20201019_0105'),
    ]

    operations = [
    ]
