# Generated by Django 3.1.1 on 2020-10-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0006_auto_20200920_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='bouquet_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
