# Generated by Django 3.1.1 on 2020-10-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_auto_20201009_0005'),
        ('bouquets', '0006_auto_20200920_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='flower',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.flower'),
        ),
    ]
