# Generated by Django 3.1.1 on 2020-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_auto_20201009_1410'),
        ('bouquets', '0007_auto_20201009_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='flower',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flower',
            field=models.ManyToManyField(
                blank=True, null=True, to='flowers.Flower'),
        ),
    ]
