# Generated by Django 3.1.1 on 2020-10-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0008_auto_20201009_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='bouquet_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
