# Generated by Django 3.1.1 on 2020-10-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0009_bouquet_bouquet_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='price',
        ),
    ]
