# Generated by Django 3.1.1 on 2020-10-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0010_remove_bouquet_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='bouquet_price',
            new_name='bouquet_paper_price',
        ),
    ]
