# Generated by Django 3.1.1 on 2020-10-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbons', '0001_initial'),
        ('wrappingPapers', '0001_initial'),
        ('bouquets', '0011_auto_20201009_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='ribbon',
            field=models.ManyToManyField(blank=True, null=True, to='ribbons.Ribbon'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='wrappingpaper',
            field=models.ManyToManyField(blank=True, null=True, to='wrappingPapers.WrappingPaper'),
        ),
    ]
