# Generated by Django 3.1.1 on 2020-10-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0012_auto_20201010_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='ribbon_color',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='wrappingpaper_color',
        ),
    ]
