# Generated by Django 3.1.1 on 2020-10-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_choice',
            field=models.CharField(choices=[('U', 'User'), ('S', 'Shop')], max_length=1, null=True),
        ),
    ]
