# Generated by Django 3.1.1 on 2020-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201015_1059'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='newuser',
        #     name='is_superuser',
        #     field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        # ),
        migrations.AddField(
            model_name='newuser',
            name='user_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
