# Generated by Django 3.1.1 on 2020-10-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201019_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
    ]
