# Generated by Django 3.1.1 on 2020-10-20 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquet', models.CharField(max_length=100)),
                ('flower', models.CharField(max_length=100)),
                ('flower_count', models.IntegerField(default=1)),
                ('ribbon', models.CharField(max_length=100)),
                ('wrappingPaper', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
