# Generated by Django 3.1.1 on 2020-10-20 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0003_auto_20201019_0105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers', '0001_initial'),
        ('shops', '0001_initial'),
        ('bouquet_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet_order',
            name='bouquet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bouquets.bouquet'),
        ),
        migrations.AlterField(
            model_name='bouquet_order',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.flower'),
        ),
        migrations.AlterField(
            model_name='bouquet_order',
            name='ribbon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bouquet_order',
            name='shops',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='bouquet_order',
            name='users',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bouquet_order',
            name='wrappingPaper',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
