# Generated by Django 3.0.8 on 2020-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_location', models.CharField(max_length=200)),
                ('shop_florist', models.CharField(max_length=50)),
                ('shop_description', models.CharField(max_length=300)),
                ('shop_phone', models.CharField(max_length=50)),
                ('shop_instagram', models.CharField(max_length=100)),
                ('shop_facebook', models.CharField(max_length=100)),
            ],
        ),
    ]
