# Generated by Django 3.0.8 on 2020-07-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20200725_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_florist',
            new_name='florist',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_phone',
            new_name='phone',
        ),
    ]
