# Generated by Django 3.0.8 on 2020-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=100)),
                ('flower_mean', models.CharField(max_length=100)),
                ('flower_season', models.CharField(max_length=20)),
                ('flower_color', models.CharField(max_length=10)),
            ],
        ),
    ]
