# Generated by Django 3.1.1 on 2020-10-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='image')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('shops', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
