# Generated by Django 3.0.8 on 2020-07-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='flower_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='flower_mean',
            new_name='mean',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='flower_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='flower_season',
            new_name='season',
        ),
    ]
