# Generated by Django 3.0.8 on 2020-08-04 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('flowers', '0002_remove_flower_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='shops',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
    ]
