# Generated by Django 3.0.8 on 2020-07-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_flower_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='mean',
            new_name='description',
        ),
    ]
