# Generated by Django 3.1.1 on 2020-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flower_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
